INSERT INTO `category` (`NAME`) VALUES
	('agios'),
	('Alimentation'),
	('assurance enfant'),
	('assurance habitation'),
	('autre revenu'),
	('cadeaux'),
	('caf'),
	('coiffure'),
	('cpam'),
	('credit'),
	('divers'),
	('edf'),
	('electromenager'),
	('emprunt'),
	('epargne'),
	('formule compte'),
	('frais bancaire'),
	('frais de garde'),
	('hygiène'),
	('impôt sur revenu'),
	('indemnite'),
	('jeux'),
	('laboratoire'),
	('loisirs'),
	('loyer'),
	('medecin'),
	('mobile'),
	('mutuelle'),
	('navigo'),
	('net'),
	('pharmacie'),
	('psy'),
	('reliquat'),
	('reparation moto'),
	('salaire fanny'),
	('salaire oumar'),
	('taxe habitation'),
	('taxi'),
	('ticket'),
	('vacances'),
	('vêtements');

