INSERT INTO `category` (`NAME`,`INCOME`) VALUES
	('agios',false),
	('Alimentation',false),
	('assurance enfant',false),
	('assurance habitation',false),
	('autre revenu',true),
	('cadeaux',false),
	('caf',true),
	('coiffure',false),
	('cpam',true),
	('credit',false),
	('edf',false),
	('electromenager',false),
	('emprunt',false),
	('epargne',false),
	('formule compte',false),
	('frais bancaire',false),
	('frais de garde',false),
	('hygiène',false),
	('impôt sur revenu',false),
	('indemnite',false),
	('jeux',false),
	('laboratoire',false),
	('loisirs',false),
	('loyer',false),
	('medecin',false),
	('mobile',false),
	('mutuelle',false),
	('navigo',false),
	('net',false),
	('pharmacie',false),
	('psy',false),
	('reliquat',false),
	('salaire',true),
	('taxe habitation',false),
	('taxi',false),
	('ticket',false),
	('vacances',false),
	('vêtements',false);

