/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP DATABASE IF EXISTS `ebudget`;
CREATE DATABASE IF NOT EXISTS `ebudget` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `ebudget`;

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY (`NAME`),
  UNIQUE KEY `NAME` (`NAME`),
  UNIQUE KEY `NAME_2` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `periode`;
CREATE TABLE IF NOT EXISTS `periode` (
  `annee` int(11) NOT NULL,
  `mois` int(11) NOT NULL,
  `trimestre` int(11) NOT NULL,
  PRIMARY KEY (`annee`,`mois`,`trimestre`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `transaction`;
CREATE TABLE IF NOT EXISTS `transaction` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `amount` double NOT NULL,
  `Date` varchar(255) NOT NULL,
  `Description` varchar(100) NOT NULL,
  `Payment` varchar(100) NOT NULL,
  `annee` int(11) NOT NULL,
  `trimestre` int(11) NOT NULL,
  `mois` int(11) NOT NULL,
  `Category` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `ID_2` (`ID`),
  KEY `FKE30A7ABE419CDCEB` (`annee`,`trimestre`,`mois`),
  KEY `FKE30A7ABEBC113A3F` (`Category`),
  CONSTRAINT `FKE30A7ABE419CDCEB` FOREIGN KEY (`annee`, `trimestre`, `mois`) REFERENCES `periode` (`annee`, `mois`, `trimestre`),
  CONSTRAINT `FKE30A7ABEBC113A3F` FOREIGN KEY (`Category`) REFERENCES `category` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
