INSERT INTO `category` (`NAME`) VALUES
	('agios'),
	('alimentation'),
	('assurance enfant'),
	('assurance habitation'),
	('autre revenu'),
	('cadeaux'),
	('caf'),
	('coiffure'),
	('cpam'),
	('crédit'),
	('divers'),
	('edf'),
	('électroménager'),
	('emprunt'),
	('épargne'),
	('formule compte'),
	('frais bancaire'),
	('frais de garde'),
	('hygiène'),
	('imp�ts'),
	('indemnité'),
	('jeux'),
	('laboratoire'),
	('loisirs'),
	('loyer'),
	('médecin'),
	('mobile'),
	('mutuelle'),
	('navigo'),
	('net'),
	('pharmacie'),
	('psy'),
	('reliquat'),
	('salaire fanny'),
	('salaire oumar'),
	('taxe habitation'),
	('taxi'),
	('ticket'),
	('vacances'),
	('vêtements');

